version: '3'
services:
  tensorflow:
    image: tensorflow/tensorflow:latest-gpu-jupyter
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports: 
      - 8888:8888
    volumes: 
      - .:/tf
